services:
  frontend:
    build:
      context: ./frontend
    container_name: triangleoflove-frontend
    ports:
      - "5173"

  backend:
    build:
      context: ./backend
    container_name: triangleoflove-backend
    ports:
      - "8080"
    depends_on:
      - db

  db:
    build:
      context: ./db
    container_name: triangleoflove-db
    environment:
      - POSTGRES_DB=triangleoflove
      - POSTGRES_USER=triangle
      - POSTGRES_PASSWORD=triangle

  api-tests:
    build:
      context: ./api-tests
    container_name: triangleoflove-api-tests
    environment:
      - API_BASE_URL=http://backend:8080
      - FRONTEND_BASE_URL=http://frontend:5173
    depends_on:
      - backend
      - frontend
    profiles:
      - tests
